Repository skywinder/ActionSheetPicker-3.0, pull requests merged in 2019-12, with the labels that each got.

#404 Fix leaked memory when present Popoverview on iPad
  Pickers/AbstractActionSheetPicker.m
Labels: bug

#444 fix iOS 13 popover layout (toolbar cut)
  Pickers/AbstractActionSheetPicker.m
Labels: bug, iPad, ios13

#451 Add contributorsi & update readme
  .all-contributorsrc
  README.md
Labels: documentation

#456 Add Discord link and fix some minor issues in README.md file
  README.md
Labels: documentation
